### ISSUE TITLE
0.0.19和0.0.15区别大吗？好像.19 不能用哎

### ISSUE THREAD

**Issue by Pancake-Q** [cpf121/vue3-uploader#3]
0.0.19和0.0.15区别大吗？好像.19 不能用，import不出内容

**Comment by cpf121** [comment]
我看了下没啥问题，你那边是有啥报错吗，方便把错误贴出来吗

**Comment by Pancake-Q** [comment]
0.0.19
![image](https://user-images.githubusercontent.com/81684567/217691288-95245368-b13e-4b48-a69b-247531ebaada.png)
0.0.15
![image](https://user-images.githubusercontent.com/81684567/217691587-572ce024-0103-4fa1-ba87-bdcb6ebc8976.png)

**Comment by cpf121** [comment]
import {uploader} from 'vue3-uploader'
你试试这样写

**Comment by cpf121** [comment]
1
